# Site settings
title: Heimdall Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://docs.iamheimdall.com"

# Author information
author: Heimdall Team
  # email: your-email@example.com
  # twitter: your-twitter-handle
  # github: your-github-handle

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag

# Minima theme settings
minima:
  date_format: "%b %-d, %Y"

# Show excerpts on the home page
show_excerpts: true

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md
  - .gitignore

# Navigation - Links to appear in the site header
header_pages:
  - about.md

# Google Analytics (empty now)
# google_analytics: (fill later with ID)

# Default permalink style
permalink: /:year/:month/:day/:title/

# Defaults for posts
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Heimdall Team"